version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '5000:5000'
    environment:
      - NODE_ENV=production
    volumes:
      - '.:/app'
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 85:80
    depends_on:
      - web
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:     
      - dbdata:/data/db
    ports:
      - '27017:27017'
volumes:
  dbdata:
  node_modules: 
